version: '2'

services:
  finrem-citizen-ui:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    ports:
      - '3100:3100'
    depends_on:
      - redis

  redis:
      image: redis:8-alpine
      ports:
          - '6379:6379'
